### ISSUE TITLE
Not working with 5.5.0 Kibana Version

### ISSUE THREAD

**Issue by source-ram** [mstoyano/TFG#22]
log   [13:25:02.924] [fatal] Error: Optimizations failure.

    ERROR in ./plugins/c3_charts/public/c3_vis.js
    Module not found: Error: Cannot resolve 'file' or 'directory' ../node_modules/c3/c3.css in /usr/share/kibana/plugins/c3_charts/public
     @ ./plugins/c3_charts/public/c3_vis.js 33:0-36
    
    ERROR in ./plugins/c3_charts/public/c3_vis_controller.js
    Module not found: Error: Cannot resolve module 'c3' in /usr/share/kibana/plugins/c3_charts/public
     @ ./plugins/c3_charts/public/c3_vis_controller.js 23:9-22

    at Object.exports.create (/usr/share/kibana/node_modules/boom/lib/index.js:21:17)
    at FsOptimizer.failedStatsToError (/usr/share/kibana/src/optimize/base_optimizer.js:233:27)
    at /usr/share/kibana/src/optimize/fs_optimizer.js:33:30
    at Compiler.<anonymous> (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:181:13)
    at /usr/share/kibana/node_modules/webpack/lib/Compiler.js:403:12
    at Compiler.next (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:67:11)
    at Compiler.<anonymous> (/usr/share/kibana/node_modules/webpack/lib/CachePlugin.js:40:4)
    at Compiler.applyPluginsAsync (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:71:13)
    at Compiler.<anonymous> (/usr/share/kibana/node_modules/webpack/lib/Compiler.js:400:9)
    at Compilation.<anonymous> (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:577:13)
    at Compilation.applyPluginsAsync (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:60:69)
    at Compilation.<anonymous> (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:572:10)
    at Compilation.next (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:67:11)
    at Compilation.<anonymous> (/usr/share/kibana/node_modules/webpack/lib/optimize/UglifyJsPlugin.js:140:4)
    at Compilation.applyPluginsAsync (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:71:13)
    at Compilation.<anonymous> (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:567:9)
    at Compilation.next (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:67:11)
    at ExtractTextPlugin.<anonymous> (/usr/share/kibana/node_modules/extract-text-webpack-plugin/index.js:303:4)
    at Compilation.applyPluginsAsync (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:71:13)
    at Compilation.<anonymous> (/usr/share/kibana/node_modules/webpack/lib/Compilation.js:563:8)
    at Compilation.next (/usr/share/kibana/node_modules/tapable/lib/Tapable.js:67:11)
    at ExtractTextPlugin.<anonymous> (/usr/share/kibana/node_modules/extract-text-webpack-plugin/index.js:279:5)
FATAL { Error: Optimizations failure.

**Comment by ajwenzel** [comment]
The same error occurs if you don't run the command 'npm install' inside your c3_charts folder in /kibana/plugins so make sure you have done this. @source-ram

**Comment by source-ram** [comment]
Followed the instructions including mom I stall and same steps works up to version 5.4.2. @ajwenzel

**Comment by RMKD** [comment]
You may be having errors related to the import syntax for 5.5 see https://github.com/elastic/kibana/issues/12707

**Comment by isqrd** [comment]
@RMKD was correct.  Fixed, and created pull request #23  that includes support for 5.5.x
